# Generated by Django 5.0.6 on 2024-05-25 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatePricePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(blank=True, choices=[('MOBILE', 'Mobile'), ('WEB', 'Web'), ('CONSULTANCY', 'Consultancy needed')], max_length=255)),
                ('stage', models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('PROTOTYPESPECIFICATION', 'Prototype/Specification'), ('DESIGNED_SOLUTIONS', 'Designed solution'), ('MVP', 'MVP')], max_length=255)),
                ('role', models.CharField(blank=True, choices=[('PM', 'Project Manager'), ('BA', 'Business Analyst'), ('UIX', 'UI/UX Designer'), ('DV', 'Developer')], max_length=255)),
                ('duration', models.CharField(blank=True, choices=[('one_month', '1 month'), ('two_months', '2 months'), ('three_months', '3 months'), ('four_months', '4 months'), ('five_months', '5 months'), ('six_months', '6 months'), ('seven_months', '7 months'), ('eight_months', '8 months'), ('nine_months', '9 months'), ('ten_months', '10 months'), ('one_year', '1 year +')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
