# Generated by Django 5.0.6 on 2024-05-25 17:25

import django.db.models.deletion
import wagtail.contrib.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_delete_calculatepricepage'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(blank=True, choices=[('MOBILE', 'Mobile'), ('WEB', 'Web'), ('CONSULTANCY', 'Consultancy needed')], max_length=50, null=True)),
                ('stage', models.CharField(blank=True, choices=[('IDEA', 'Idea'), ('PROTOTYPESPECIFICATION', 'Prototype/Specification'), ('DESIGNED_SOLUTIONS', 'Designed solution'), ('MVP', 'MVP')], max_length=50, null=True)),
                ('role', models.CharField(blank=True, choices=[('PM', 'Project Manager'), ('BA', 'Business Analyst'), ('UIX', 'UI/UX Designer'), ('DV', 'Developer')], max_length=50, null=True)),
                ('duration', models.CharField(blank=True, choices=[('one_month', '1 month'), ('two_months', '2 months'), ('three_months', '3 months'), ('four_months', '4 months'), ('five_months', '5 months'), ('six_months', '6 months'), ('seven_months', '7 months'), ('eight_months', '8 months'), ('nine_months', '9 months'), ('ten_months', '10 months'), ('one_year', '1 year +')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
    ]
