# Generated by Django 5.0.6 on 2024-05-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_formfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormSubmission',
        ),
    ]
