# Generated by Django 5.0.6 on 2024-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='to_address',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
