# Generated by Django 5.0.6 on 2024-05-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contactpage_from_address_contactpage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='contact_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contacts.contactpage'),
        ),
    ]
