# Generated by Django 5.0.6 on 2024-06-11 11:37

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contactpage_thank_you_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='contact_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contacts.contactpage'),
        ),
    ]
