# Generated by Django 5.0.6 on 2024-06-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_formpage_remove_contactpage_page_ptr_and_more'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customformsubmission',
            unique_together={('page',)},
        ),
        migrations.RemoveField(
            model_name='customformsubmission',
            name='user',
        ),
    ]
