# Generated by Django 5.0.6 on 2024-06-11 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_calculateformpage_calculatecustomformsubmission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculatecustomformsubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customformsubmission',
            options={},
        ),
    ]
