# Generated by Django 5.0.6 on 2024-06-11 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_alter_calculatecustomformsubmission_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculateFormField',
        ),
    ]
