# Generated by Django 5.0.6 on 2024-06-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_delete_calculateformfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateformpage',
            name='your_email',
            field=models.EmailField(default='', help_text='Your Email', max_length=254),
        ),
        migrations.AddField(
            model_name='calculateformpage',
            name='your_name',
            field=models.CharField(default='', help_text='Your Name', max_length=255),
        ),
    ]
