# Generated by Django 5.0.6 on 2024-06-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_alter_formfield_field_type_delete_fileformfield'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='ContactsPage',
        ),
        migrations.RenameModel(
            old_name='CustomFormSubmission',
            new_name='CustomContactsFormSubmission',
        ),
    ]
