# Generated by Django 5.0.6 on 2024-06-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_alter_formfield_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculateformpage',
            name='your_email',
        ),
        migrations.RemoveField(
            model_name='calculateformpage',
            name='your_name',
        ),
    ]
