# Generated by Django 5.0.6 on 2024-06-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_remove_calculateformpage_your_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculateformpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='calculateformpage',
            name='thank_you_text',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='contactspage',
            name='thank_you_text',
        ),
    ]
