version: "3.3"

services:
  db:
    env_file: .env
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    environment:
      - DJANGO_DEVELOPMENT=True
    restart: always
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
#  ui:
#    build:
#      context: ../devcons
#      dockerfile: ./Dockerfile  # Ensure Dockerfile path is correct relative to context
#    ports:
#      - "3000:3000"
#    depends_on:
#      - app
#    env_file:
#      - ../devcons/.env
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
