version: "3.3"

services:
  db:
    env_file: .env
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    environment:
      - DJANGO_DEVELOPMENT=True
    restart: always
    build: .
    command: [ "sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:80" ]
    volumes:
      - .:/app
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
#  ui:
#    build:
#      context: ../devcons
#      dockerfile: ./Dockerfile  # Ensure Dockerfile path is correct relative to context
#    ports:
#      - "80:80"
#    depends_on:
#      - app
#    env_file:
#      - ../devcons/.env