# Generated by Django 5.0.6 on 2024-05-25 16:48

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceslistpage_servicesimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceslistpage',
            name='services',
            field=wagtail.fields.StreamField([('services', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Services', max_length=250, required=True)), ('services', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Service Title', max_length=100, required=True)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.blocks.PageChooserBlock(required=False))])))]))], blank=True, null=True),
        ),
    ]
