# Generated by Django 5.0.6 on 2024-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
