# Generated by Django 5.0.6 on 2024-05-25 13:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homepage_subtitle_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
