# Generated by Django 5.0.6 on 2024-05-25 13:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_stat_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='description',
            field=wagtail.fields.RichTextField(),
        ),
    ]
