# Generated by Django 5.0.6 on 2024-05-25 15:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_aboutpage_aboutimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'About Page', 'verbose_name_plural': 'About Pages'},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='company_description',
            field=wagtail.fields.RichTextField(null=True),
        ),
    ]
