# Generated by Django 5.0.6 on 2024-05-25 16:15

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_aboutpage_options_and_more'),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='team_members',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='snippets.teammember'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='trusted_partners',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='snippets.trustedpartner'),
        ),
    ]
