# Generated by Django 5.0.6 on 2024-05-25 16:34

import streams.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aboutpage_team_members_aboutpage_trusted_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('services', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Services', max_length=250, required=True)), ('services', wagtail.blocks.ListBlock(streams.blocks.ServiceBlock))]))], blank=True, null=True),
        ),
    ]
